name: Docker Build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile -t docker.pkg.github.com/shz/human-preservation-initiative/web:${{ github.sha }} -t docker.pkg.github.com/shz/human-preservation-initiative/web:latest
    - name: Docker Login
      run: docker login docker.pkg.github.com -u shz -p ${{ secrets.PACKAGES_TOKEN }}
    - name: Docker Publish
      run: |
        docker push docker.pkg.github.com/shz/human-preservation-initiative/web:${{ github.sha }}
        docker push docker.pkg.github.com/shz/human-preservation-initiative/web:latest
